version: 2

image: &image
    docker:
      - image: gentoo/stage3:systemd-20201118
    environment:
      target: "Z390"


setup_env: &setup_env
    name: Prepare env
    command: |
      emerge -q dev-vcs/git eix jq
      eix-update

      git clone https://github.com/pgrandin/stage4.git /root/project/
      cd /root/project
      git checkout config_based
      rsync -vrtza files/Z390/ /
      rsync -vrtza ubuntu@packages.kazer.org:/packages/$target/binpkgs/ /var/cache/binpkgs/ -e "ssh -o StrictHostKeyChecking=no"

upload_packages: &upload_packages
    name: Upload packages
    command: |
      if [[ -d "/var/cache/binpkgs/binpkgs/" ]]; then
        mv /var/cache/binpkgs/binpkgs/* /var/cache/binpkgs/
        rmdir /var/cache/binpkgs/binpkgs
      fi
      rsync -vrtza ubuntu@packages.kazer.org:/packages/$target/binpkgs/ /var/cache/binpkgs/ -e "ssh -o StrictHostKeyChecking=no"
      emaint binhost --fix
      rsync -vrtza --delete /var/cache/binpkgs -e "ssh -o StrictHostKeyChecking=no" ubuntu@packages.kazer.org:/packages/$target/

jobs:
  emerge_sync:
    <<: *image
    steps:
      - attach_workspace:
            at: /var/db/repos/
      - run:
          name: emerge-webrsync
          command: |
            emerge-webrsync
      - persist_to_workspace:
          root: /var/db/repos/
          paths:
            - ./gentoo

  build_kernel:
    <<: *image
    steps:
      - attach_workspace:
            at: /var/db/repos/
      - run: *setup_env
      - run:
          name: Prepare kernel build
          command: |
            git clone https://github.com/pgrandin/kernel-configs.git /tmp/kernel-configs-master/
            pushd /tmp/kernel-configs-master/
            kconfig_sha=$(git rev-parse HEAD)
            popd

            echo "${kversion}-${kconfig_sha}" > kernel-config.txt
            cp kernel-config.txt /var/db/repos/kernel-config.txt # for workspace persistence
            cat /var/db/repos/kernel-config.txt

      - restore_cache:
          key: kernel-v1-{{ checksum "/var/db/repos/kernel-config.txt" }}
      - run:
          name: Build kernel
          command: |
            kversion=$(eix gentoo-source|awk -F'[()]' '/ [~]5.8/ {version=$2} END{print version}')

            if [[ -e "/usr/src/linux-${kversion}-gentoo/arch/x86_64/boot/bzImage" ]]; then
              echo "Found kernel from cache, skipping compilation"
            else
              echo "=sys-kernel/gentoo-sources-$kversion ~amd64" > /etc/portage/package.keywords/gentoo-sources
              MAKEOPTS="-j$(nproc)" FEATURES="-getbinpkg" emerge -q =gentoo-sources-$kversion

              cd /usr/src/linux
              cat arch/x86/configs/x86_64_defconfig /tmp/kernel-configs-master/common_defconfig > arch/x86/configs/${target}_defconfig

              confs=$(cat /root/project/config.json | jq --arg HOST target -r '.configs[] | select (.["host"]==$HOST) | .kernel_configs |.[]' )
              for conf in $confs; do
                  cat /tmp/kernel-configs-master/${conf}_defconfig >> arch/x86/configs/${target}_defconfig
              done
              cat /tmp/kernel-configs-master/${target}_defconfig >> arch/x86/configs/${target}_defconfig
              make defconfig ${target}_defconfig
              make -j$(nproc)
            fi
      - save_cache:
          paths:
            - /usr/src/
          key: kernel-v1-{{ checksum "/var/db/repos/kernel-config.txt" }}
      - persist_to_workspace:
          root: /var/db/repos/
          paths:
            - ./kernel-config.txt


  build_llvm_10:
    <<: *image
    steps:
      - attach_workspace:
            at: /var/db/repos/
      - run: *setup_env
      - run:
          name: Build llvm 10
          command: |
            llvm_ver=$(eix -e sys-devel/llvm -xl|grep -v '\*\*' | grep '(10)'| tail -1|cut -c 13-|cut -f1 -d" ")
            MAKEOPTS="-j4" emerge -1 =sys-devel/llvm-${llvm_ver}
            rsync -vrtza --delete /var/cache/binpkgs/sys-devel/llvm*-10.* -e "ssh -o StrictHostKeyChecking=no" ubuntu@packages.kazer.org:/packages/$target/binpkgs/sys-devel/

  build_llvm_11:
    <<: *image
    steps:
      - attach_workspace:
            at: /var/db/repos/
      - run: *setup_env
      - run:
          name: Build llvm 11
          command: |
            llvm_ver=$(eix -e sys-devel/llvm -xl|grep -v '\*\*' | grep '(11)'| tail -1|cut -c 13-|cut -f1 -d" ")
            MAKEOPTS="-j4" emerge -1 =sys-devel/llvm-${llvm_ver}
            rsync -vrtza --delete /var/cache/binpkgs/sys-devel/llvm*-11.* -e "ssh -o StrictHostKeyChecking=no" ubuntu@packages.kazer.org:/packages/$target/binpkgs/sys-devel/

  build_boost:
    <<: *image
    steps:
      - attach_workspace:
            at: /var/db/repos/
      - run: *setup_env
      - run:
          name: Build boost
          command: |
            MAKEOPTS="-j2" emerge -1 dev-libs/boost
            rsync -vrtza --delete /var/cache/binpkgs/dev-libs/boost* -e "ssh -o StrictHostKeyChecking=no" ubuntu@packages.kazer.org:/packages/$target/binpkgs/dev-libs/

  synchronize_steps:
    <<: *image
    steps:
      - attach_workspace:
            at: /var/db/repos/
      - run: *upload_packages

  build_system:
    <<: *image
    steps:
      - attach_workspace:
            at: /var/db/repos/
      - run: *setup_env
      - restore_cache:
          key: kernel-v1-{{ checksum "/var/db/repos/kernel-config.txt" }}
      - run:
          name: Build @system
          command: |
            emerge -uq libudev # for elogind
            MAKEOPTS="-j$(nproc)" emerge -NDuq @system
      - run: *upload_packages

  build_set1:
    <<: *image
    steps:
      - attach_workspace:
            at: /var/db/repos/
      - run: *setup_env
      - restore_cache:
          key: kernel-v1-{{ checksum "/var/db/repos/kernel-config.txt" }}
      - run:
          name: Build partial @world
          command: |
            env -u target MAKEOPTS="-j$(nproc)" emerge -NDuq dev-util/pycharm-community
      - run: *upload_packages

  build_set2:
    <<: *image
    steps:
      - attach_workspace:
            at: /var/db/repos/
      - run: *setup_env
      - restore_cache:
          key: kernel-v1-{{ checksum "/var/db/repos/kernel-config.txt" }}
      - run:
          name: Build partial @world
          command: |
            env -u target MAKEOPTS="-j$(nproc)" emerge -NDuq dev-util/pycharm-community
      - run: *upload_packages

  build_firefox_deps:
    <<: *image
    steps:
      - attach_workspace:
            at: /var/db/repos/
      - run: *setup_env
      - restore_cache:
          key: kernel-v1-{{ checksum "/var/db/repos/kernel-config.txt" }}
      - run:
          name: Build partial @world
          command: |
            env -u target MAKEOPTS="-j$(nproc)" emerge -NDuqo www-client/firefox mail-client/thunderbird
      - run: *upload_packages

  build_chromium_deps:
    <<: *image
    steps:
      - attach_workspace:
            at: /var/db/repos/
      - run: *setup_env
      - restore_cache:
          key: kernel-v1-{{ checksum "/var/db/repos/kernel-config.txt" }}
      - run:
          name: Build partial @world
          command: |
            env -u target MAKEOPTS="-j$(nproc)" emerge -NDuqo www-client/chromium
      - run: *upload_packages


workflows:
  version: 2
  main:
    jobs:
      - emerge_sync
      - build_kernel:
          requires:
            - emerge_sync
      - build_llvm_10:
          requires:
            - emerge_sync
      - build_llvm_11:
          requires:
            - emerge_sync
      - build_boost:
          requires:
            - emerge_sync
      - synchronize_steps:
          requires:
              - build_llvm_10
              - build_llvm_11
              - build_boost
      - build_system:
          requires:
            - synchronize_steps
            - build_kernel
      - build_set1:
          requires:
            - build_system
      - build_set2:
          requires:
            - build_set1
      - build_firefox_deps:
          requires:
            - build_set2
      - build_chromium_deps:
          requires:
            - build_firefox_deps