version: 2.1

image: &image
    docker:
      - image: pgrandin/stage4-ci:$CIRCLE_BUILD_NUM
    environment:
      target: "Z390"
      FEATURES: "-sandbox -usersandbox"


setup_env: &setup_env
    name: Prepare env
    command: |
      git clone https://github.com/pgrandin/stage4.git /root/project/
      cd /root/project
      git checkout config_based
      rsync -vrtza files/<< parameters.target >>/ /
      rsync -vrtza ubuntu@packages.kazer.org:/packages/<< parameters.target >>/binpkgs/ /var/cache/binpkgs/ -e "ssh -o StrictHostKeyChecking=no"
      emaint binhost --fix

upload_packages: &upload_packages
    name: Upload packages
    command: |
      if [[ -d "/var/cache/binpkgs/binpkgs/" ]]; then
        mv /var/cache/binpkgs/binpkgs/* /var/cache/binpkgs/
        rmdir /var/cache/binpkgs/binpkgs
      fi
      rsync -vrtza ubuntu@packages.kazer.org:/packages/$target/binpkgs/ /var/cache/binpkgs/ -e "ssh -o StrictHostKeyChecking=no"
      emaint binhost --fix
      rsync -vrtza --delete /var/cache/binpkgs -e "ssh -o StrictHostKeyChecking=no" ubuntu@packages.kazer.org:/packages/$target/


jobs:
  emerge_sync:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: build docker image
          command: |
            cd dockr
            docker build -t pgrandin/stage4-ci:$CIRCLE_BUILD_NUM
            docker login -e $DOCKER_HUB_EMAIL -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
            docker push pgrandin/stage4-ci:$CIRCLE_BUILD_NUM

  synchronize_steps:
    <<: *image
    parameters:
      target:
        type: string
    steps:
      - attach_workspace:
            at: /var/db/repos/
      - run: *upload_packages

  build_kernel:
    <<: *image
    parameters:
      target:
        type: string
    steps:
      - attach_workspace:
            at: /var/db/repos/
      - run: *setup_env
      - run:
          name: Prepare kernel build
          command: |
            git clone https://github.com/pgrandin/kernel-configs.git /tmp/kernel-configs-master/
            pushd /tmp/kernel-configs-master/
            kconfig_sha=$(git rev-parse HEAD)
            popd

            kversion=$(eix gentoo-source|awk -F'[()]' '/ [~]5.10/ {version=$2} END{print version}')
            echo "${kversion}-${kconfig_sha}" > kernel-config.txt
            cp kernel-config.txt /var/db/repos/kernel-config.txt # for workspace persistence
            cat /var/db/repos/kernel-config.txt

      - restore_cache:
          key: kernel-v1-{{ checksum "/var/db/repos/kernel-config.txt" }}
      - run:
          name: Build kernel
          command: |
            kversion=$(eix gentoo-source|awk -F'[()]' '/ [~]5.10/ {version=$2} END{print version}')

            if [[ -e "/usr/src/linux-${kversion}-gentoo/arch/x86_64/boot/bzImage" ]]; then
              echo "Found kernel from cache, skipping compilation"
            else
              mkdir /etc/portage/package.keywords/
              echo "=sys-kernel/gentoo-sources-$kversion ~amd64" > /etc/portage/package.keywords/gentoo-sources
              MAKEOPTS="-j$(nproc)" FEATURES="-getbinpkg" emerge -q =gentoo-sources-$kversion

              cd /usr/src/linux
              cat arch/x86/configs/x86_64_defconfig /tmp/kernel-configs-master/common_defconfig > arch/x86/configs/${target}_defconfig

              confs=$(cat /root/project/config.json | jq --arg HOST target -r '.configs[] | select (.["host"]==$HOST) | .kernel_configs |.[]' )
              for conf in $confs; do
                  cat /tmp/kernel-configs-master/${conf}_defconfig >> arch/x86/configs/${target}_defconfig
              done
              cat /tmp/kernel-configs-master/${target}_defconfig >> arch/x86/configs/${target}_defconfig
              make defconfig ${target}_defconfig
              make -j$(nproc)
            fi
      - save_cache:
          paths:
            - /usr/src/
          key: kernel-v1-{{ checksum "/var/db/repos/kernel-config.txt" }}
      - persist_to_workspace:
          root: /var/db/repos/
          paths:
            - ./kernel-config.txt


  build_package_oneshot:
    <<: *image
    parameters:
      package:
        type: string
      target:
        type: string
    steps:
      - attach_workspace:
            at: /var/db/repos/
      - run: *setup_env
      - run:
          name: Build one package
          command: |
            package="<< parameters.package >>*"
            atom="${package/\*-/:}"
            atom="${atom/\*/}"
            atom="${atom/\./}"
            category=$(echo $package | cut -d'/' -f1)
            echo "$package -> $atom -> $category"

            MAKEOPTS="-j2" emerge -1 ${atom}
            rsync -vrtza --delete /var/cache/binpkgs/${package} -e "ssh -o StrictHostKeyChecking=no" ubuntu@packages.kazer.org:/packages/$target/binpkgs/${category}/

  build_package:
    <<: *image
    parameters:
      target:
        type: string
      package:
        type: string
      emerge_flags:
        type: string
    steps:
      - attach_workspace:
            at: /var/db/repos/
      - run: *setup_env
      - run:
          name: Build one package deps
          command: |
            if [ $(grep "www-client/firefox" /var/lib/portage/world) ]; then
              env -u target MAKEOPTS="-j$(nproc)" emerge << parameters.emerge_flags >> << parameters.package >>
            else
              echo "Package << parameters.package >> not in world file, skipping"
            fi
      - run: *upload_packages

  build_system:
    <<: *image
    parameters:
      target:
        type: string
    steps:
      - attach_workspace:
            at: /var/db/repos/
      - run: *setup_env
      - restore_cache:
          key: kernel-v1-{{ checksum "/var/db/repos/kernel-config.txt" }}
      - run:
          name: Build @system
          command: |
            emerge -uq libudev # for elogind
            MAKEOPTS="-j$(nproc)" emerge -NDuq @system --jobs $(nproc)
          no_output_timeout: 90m
      - run: *upload_packages

  build_world:
    <<: *image
    parameters:
      target:
        type: string
    steps:
      - attach_workspace:
            at: /var/db/repos/
      - run: *setup_env
      - restore_cache:
          key: kernel-v1-{{ checksum "/var/db/repos/kernel-config.txt" }}
      - run:
          name: Build @world
          command: |
            MAKEOPTS="-j$(nproc)" emerge -NDuq @world --jobs $(nproc)
          no_output_timeout: 90m
      - run: *upload_packages

  perl_cleanup:
    <<: *image
    steps:
      - attach_workspace:
            at: /var/db/repos/
      - run: *setup_env
      - restore_cache:
          key: kernel-v1-{{ checksum "/var/db/repos/kernel-config.txt" }}
      - run:
          name: Clean up perl installation
          command: |
            emerge -q1 dev-lang/perl
            FEATURES="-getbinpkg" emerge -q1 XML-Parser
            perl-cleaner --reallyall
      - run: *upload_packages


workflow_jobs: &workflow_jobs
    jobs:
      - emerge_sync
      - build_kernel:
          requires:
            - emerge_sync
          matrix:
            alias: kernel
            parameters:
              target: ["Z390", "R710"]
      - build_package_oneshot:
          name: pre-<< matrix.package >>-<< matrix.target >>
          requires:
            - emerge_sync
          matrix:
            alias: pre-
            parameters:
              package: ["sys-devel/llvm*-10.", "sys-devel/llvm*-11.", "dev-lang/rust", "net-libs/nodejs", "dev-libs/boost", "sys-devel/clang", "sys-devel/gcc"]
              target: ["Z390", "R710"]
            exclude:
              - R710: dev-lang/rust
              - R710: net-libs/nodejs
      - synchronize_steps:
          name: sync-<< matrix.target >>
          requires:
            - pre-sys-devel/llvm*-10.-<< matrix.target >>
            - pre-sys-devel/llvm*-11.-<< matrix.target >>
            - pre-dev-lang/rust-<< matrix.target >>
            - pre-net-libs/nodejs-<< matrix.target >>
            - pre-dev-libs/boost-<< matrix.target >>
            - pre-sys-devel/clang-<< matrix.target >>
            - pre-sys-devel/gcc-<< matrix.target >>
          matrix:
            alias: sync-
            parameters:
              target: ["Z390", "R710"]
      - build_system:
          requires:
            - build_kernel-<< matrix.target >>
            - sync-<< matrix.target >>
          matrix:
            alias: build_system
            parameters:
              target: ["Z390", "R710"]
      - build_package:
          name: deps-<< matrix.package >>-<< matrix.target >>
          requires:
            - build_system-<< matrix.target >>
          matrix:
            alias: deps-
            parameters:
              package: ["www-client/firefox", "www-client/chromium", "app-emulation/virt-manager", "dev-util/pycharm-community"]
              target: ["Z390", "R710"]
              emerge_flags : ["-NDuqo"]
      - build_package:
          name: build-<< matrix.package >>-<< matrix.target >>
          requires:
            - deps-<< matrix.package >>-<< matrix.target >>
          matrix:
            alias: build
            parameters:
              package: ["www-client/firefox", "www-client/chromium", "app-emulation/virt-manager", "dev-util/pycharm-community"]
              target: ["Z390", "R710"]
              emerge_flags : ["-NDuq"]
      - build_world:
          requires:
            - build-www-client/firefox-<< matrix.target >>
            - build-www-client/chromium-<< matrix.target >>
            - build-app-emulation/virt-manager-<< matrix.target >>
            - build-dev-util/pycharm-community-<< matrix.target >>
          matrix:
            alias: world-
            parameters:
              target: ["Z390", "R710"]

workflows:
  version: 2
  main:
    <<: *workflow_jobs
  nightly:
    triggers:
      - schedule:
          cron: "32 13 * * *"
          filters:
            branches:
              only:
                - config_based
    <<: *workflow_jobs
