name: 3. Package and Upload
on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Build target'
        required: true
        type: choice
        options:
          - XPS-9730
          - R710
          - R630
          - Z390
  workflow_run:
    workflows: ["2. Build System"]
    types:
      - completed

jobs:
  package:
    runs-on: [self-hosted]
    strategy:
      matrix: ${{ github.event_name == 'workflow_dispatch' && format('{"target":["%s"]}', github.event.inputs.target) || format('{"target":["%s"]}', github.event.workflow_run.head_branch) }}
      fail-fast: false
    env:
      target: ${{ matrix.target }}
      stage4_fs: "./stage4"
    steps:
      - uses: actions/checkout@v3
      
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build-${{ matrix.target }}
          path: ${{ env.stage4_fs }}

      - name: Configure and build browsers
        run: |
          cp chroot/04_configure.sh ${{ env.stage4_fs }}/04_configure.sh
          chroot ${{ env.stage4_fs }} /bin/bash /04_configure.sh ${{ env.target }}
          cp chroot/05_browsers.sh ${{ env.stage4_fs }}/05_browsers.sh
          bash ${{ env.stage4_fs }}/05_browsers.sh ${{ env.stage4_fs }}

      - name: Archive and upload
        env:
          AWS_BUCKET: pierre-packages
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          tar cfz /${target}-stage4.tgz -C ${{ env.stage4_fs }} .
          md5sum /${target}-stage4.tgz > /${target}-stage4.tgz.md5
          aws s3 cp /${target}-stage4.tgz s3://${AWS_BUCKET}/stage4/${target}/${target}-stage4.tgz
          aws s3 cp /${target}-stage4.tgz.md5 s3://${AWS_BUCKET}/stage4/${target}/${target}-stage4.tgz.md5

      - name: Upload logs
        if: always()
        env:
          AWS_BUCKET: pierre-packages
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          find "${{ env.stage4_fs }}/var/tmp/portage" -type f -name "*build.log" | while read -r file; do
            category=$(echo "$file" | awk -F'/' '{print $(NF-3)}')
            package=$(echo "$file" | awk -F'/' '{print $(NF-2)}')
            new_file_name="${category}_${package}.log"
            aws s3 cp "$file" "s3://${AWS_BUCKET}/stage4/${target}/$new_file_name"
          done

      - name: Cleanup mounts
        if: always()
        run: |
          sync
          for mount in ${{ env.stage4_fs }}/{dev/pts,dev/shm,proc,dev,var/tmp,var/cache/binpkgs,var/cache}; do
            if mountpoint -q "$mount"; then
              umount -l "$mount" || echo "Failed to unmount $mount"
            fi
          done
