name: Docker Image CI

on:
  push:
    branches: [ docker ]
  pull_request:
    branches: [ docker ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Generate today's tag
      run: echo "stage4_tag=$(date +%Y%m%d)" >> $GITHUB_ENV   
    - uses: actions/checkout@v3
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        file: Dockerfile
        tags: |
          pgrandin/stage4-ci:${{ env.stage4_tag }}
          pgrandin/stage4-ci:latest