name: Docker Image CI

on:
  push:
    branches: [ docker ]
  pull_request:
    branches: [ docker ]
  schedule:
  - cron: "0 0 * * *"    

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Generate today's tag
      run: echo "stage4_tag=$(date +%Y%m%d)" >> $GITHUB_ENV   
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2    
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}      

    - name: Check if we need to rebuild stage3
      id: check-need-build-stage3
      run: |
        RETURN_CODE=`docker manifest inspect docker.io/pgrandin/stage4-ci:stage3-${{ env.stage4_tag }} > /dev/null && echo $? || echo $?`
        docker pull docker.io/pgrandin/stage4-ci:stage3-${{ env.stage4_tag }}
        echo "::set-output name=need-build::$RETURN_CODE"

    - name: Check if we need to rebuild kernel-build
      id: check-need-build-kernel-build
      run: |
        RETURN_CODE=`docker manifest inspect docker.io/pgrandin/stage4-ci:kernel-build-${{ env.stage4_tag }} > /dev/null && echo $? || echo $?`
        echo "::set-output name=need-build::$RETURN_CODE"

    - name: Build and push stage3 step
      if: steps.check-need-build-stage3.outputs.need-build == '1'
      uses: docker/build-push-action@v3
      with:
        push: true
        file: Dockerfile
        target: stage3
        build-args: |
          today=${{ env.stage4_tag }}
        tags: |
          docker.io/pgrandin/stage4-ci:stage3-${{ env.stage4_tag }}
        cache-from: type=registry,ref=pgrandin/stage4-ci:stage3-${{ env.stage4_tag }}
        cache-to: type=registry,ref=pgrandin/stage4-ci:stage3-${{ env.stage4_tag }},mode=max          

    - name: Build and push kernel-build step
      if: steps.check-need-build-kernel-build.outputs.need-build == '1'
      uses: docker/build-push-action@v3
      with:
        push: true
        file: Dockerfile
        target: kernel-build
        build-args: |
          today=${{ env.stage4_tag }}
        tags: |
          docker.io/pgrandin/stage4-ci:kernel-build-${{ env.stage4_tag }}
        cache-from: type=registry,ref=pgrandin/stage4-ci:kernel-build-${{ env.stage4_tag }}
        cache-to: type=registry,ref=pgrandin/stage4-ci:kernel-build-${{ env.stage4_tag }},mode=max          

    - name: Build and push harfbuzz step
      uses: docker/build-push-action@v3
      with:
        push: true
        file: Dockerfile
        target: kernel-build
        build-args: |
          today=${{ env.stage4_tag }}
        tags: |
          pgrandin/stage4-ci:harfbuzz-${{ env.stage4_tag }}
        cache-from: type=registry,ref=pgrandin/stage4-ci:harbuzz-${{ env.stage4_tag }}
        cache-to: type=registry,ref=pgrandin/stage4-ci:narfbuzz-${{ env.stage4_tag }},mode=max          
